# Generated by Django 5.0.3 on 2024-03-26 02:28

import livro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0005_alter_livros_data_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='data_cadastro',
            field=models.DateTimeField(default=livro.models.default_data_cadastro),
        ),
    ]
