# Generated by Django 5.0.3 on 2024-04-01 16:19

import livro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0007_alter_livros_data_cadastro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partituras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=30)),
                ('co_autor', models.CharField(blank=True, max_length=100, null=True)),
                ('data_cadastro', models.DateTimeField(blank=True, default=livro.models.default_data_cadastro)),
                ('emprestado', models.BooleanField(default=False)),
                ('nome_emprestado', models.CharField(blank=True, max_length=30)),
                ('data_emprestimo', models.DateTimeField(blank=True)),
                ('data_devolucao', models.DateTimeField(blank=True)),
                ('tempo_emprestimo', models.TimeField(blank=True)),
            ],
            options={
                'verbose_name': 'Partitura',
            },
        ),
        migrations.DeleteModel(
            name='Livros',
        ),
    ]
