# Generated by Django 5.0.3 on 2024-04-01 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0008_partituras_delete_livros'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Partituras',
            new_name='Livros',
        ),
        migrations.AlterModelOptions(
            name='livros',
            options={'verbose_name': 'Livro'},
        ),
    ]
