# Generated by Django 5.0.4 on 2024-04-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0016_alter_livros_options_livros_exemplares_disponiveis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='arranjador',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='livros',
            name='classificacao',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livros',
            name='compositor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='livros',
            name='conteudo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livros',
            name='edicao',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livros',
            name='obra',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livros',
            name='observacao',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
