# Generated by Django 5.0.4 on 2024-04-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0017_livros_arranjador_livros_classificacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='autor',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='livros',
            name='localizacao',
            field=models.CharField(max_length=100, verbose_name='Localização'),
        ),
        migrations.AlterField(
            model_name='livros',
            name='nome',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
