# Generated by Django 5.0.4 on 2024-04-11 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0018_alter_livros_autor_alter_livros_localizacao_and_more'),
        ('usuarios', '0002_usuario_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='arranjador',
            field=models.CharField(blank=True, max_length=100, verbose_name='Arranjador'),
        ),
        migrations.AlterField(
            model_name='livros',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='livro.categoria', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='livros',
            name='classificacao',
            field=models.CharField(max_length=100, verbose_name='Classificação'),
        ),
        migrations.AlterField(
            model_name='livros',
            name='compositor',
            field=models.CharField(blank=True, max_length=100, verbose_name='Compositor'),
        ),
        migrations.AlterField(
            model_name='livros',
            name='conteudo',
            field=models.CharField(max_length=100, verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='livros',
            name='edicao',
            field=models.CharField(max_length=100, verbose_name='Edição'),
        ),
        migrations.AlterField(
            model_name='livros',
            name='obra',
            field=models.CharField(max_length=100, verbose_name='Obra'),
        ),
        migrations.AlterField(
            model_name='livros',
            name='observacao',
            field=models.CharField(max_length=100, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='livros',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuario', verbose_name='Usuário'),
        ),
    ]
