# Generated by Django 4.2.11 on 2024-04-12 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0019_alter_emprestimos_data_emprestimo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livros',
            options={'verbose_name': 'Partitura'},
        ),
        migrations.AddField(
            model_name='livros',
            name='arranjador',
            field=models.CharField(blank=True, max_length=100, verbose_name='Arranjador'),
        ),
        migrations.AddField(
            model_name='livros',
            name='classificacao',
            field=models.CharField(default=1, max_length=100, verbose_name='Classificação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livros',
            name='compositor',
            field=models.CharField(blank=True, max_length=100, verbose_name='Compositor'),
        ),
        migrations.AddField(
            model_name='livros',
            name='conteudo',
            field=models.CharField(default=1, max_length=100, verbose_name='Conteúdo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livros',
            name='edicao',
            field=models.CharField(default=1, max_length=100, verbose_name='Edição'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livros',
            name='exemplares_disponiveis',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livros',
            name='formato',
            field=models.CharField(default=1, max_length=100, verbose_name='Formato'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livros',
            name='localizacao',
            field=models.CharField(default=1, max_length=100, verbose_name='Localização'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livros',
            name='obra',
            field=models.CharField(default=1, max_length=100, verbose_name='Obra'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livros',
            name='observacao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='emprestimos',
            name='data_emprestimo',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 12, 7, 38, 28, 959209)),
        ),
    ]
