# Generated by Django 5.0.4 on 2024-04-11 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0019_alter_livros_arranjador_alter_livros_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='formato',
            field=models.CharField(default=1, max_length=100, verbose_name='Formato'),
            preserve_default=False,
        ),
    ]
