# Generated by Django 5.0.4 on 2024-04-12 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0019_alter_emprestimos_data_emprestimo'),
        ('livro', '0020_livros_formato'),
    ]

    operations = [
    ]
