# Generated by Django 4.2.11 on 2024-04-12 23:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0027_alter_emprestimos_data_emprestimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimos',
            name='data_emprestimo',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 12, 20, 52, 29, 883355)),
        ),
        migrations.AlterField(
            model_name='livros',
            name='autor',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='livros',
            name='nome',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
