# Generated by Django 4.2.11 on 2024-04-13 00:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0028_alter_emprestimos_data_emprestimo_alter_livros_autor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimos',
            name='data_emprestimo',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 12, 21, 48, 48, 86352)),
        ),
    ]
